### ISSUE TITLE
Translate

### ISSUE THREAD

**Issue by Anyelou** [Renari/Fate-Grand-Order-Translation#1]
Hello, I would like to talk to you, I am also a fan translator, and various games have translated into my language (Spanish) and I would like this to be one more. So I want you solve me a few questions about the location of files and how to do to implement the translation

**Comment by Renari** [comment]
Sorry, I don't plan on helping others with this due to the fact that I think it can be abused for malicious purposes.

**Comment by Anyelou** [comment]
Relax, do not need your translation, not looking to take advantage of your job, just looking for was some information to do what I always do with a game that we like my friends and me but that will not come into our language, translate only I want that, do not seek money or fame, just to give my friends and everyone who wants a more fun, more playable game and where they can have more fun.

If you do not want to help me, then I do not need your help, I am currently doing more translations, are free and have nothing malicious. I will overturn them until someone tells me where to find the files of this game to start translating. 

I know I make people happy with my translations and that's all that matters, I do not need someone to tell me something like what you said you, I also know that you can not trust everyone in this society in which We live, but I just, I'm not a malicious person.

**Comment by Renari** [comment]
If you care enough to actually do this, you'll be able to do this on your own. Me telling you where certain files are and how to access them can potentially allow you to change files that should not be changed. Long story short, I don't trust you, sorry.

**Comment by Anyelou** [comment]
I agree, but I had to say, I will not bother you, thanks for your time
