### ISSUE TITLE
Won't load

### ISSUE THREAD

**Issue by Bluefrost13** [Renari/Fate-Grand-Order-Translation#3]
I'm trying to use this on my Nexus 5.  I extract the files, and move them to the correct folder, but once I start the game up, after the initial white GO logo screen, the game goes to a black screen.  I can still interact with the black screen, as when I touch it the coloured squares show up, but the rest of the game doesn't load, and the loading message doesn't appear.

**Comment by Renari** [comment]
I haven't experienced this problem so I'm not sure what could cause it. Can you check the integrity of the files you downloaded?

Name: mstSkill.dat
Size: 68923 bytes (0 MB)
CRC32: C22AB4F5

Name: mstSkillDetail.dat
Size: 44955 bytes (0 MB)
CRC32: 507C0BDA

**Comment by DizzyAvocado** [comment]
Exactly the same is happening to me on my Nexus 7 5.1.1. I'll try downloading and replacing the files one more time.

**Comment by Renari** [comment]
I have a feeling this is due to windows blocking the zip file you downloaded. Do you see this on the zip file you downloaded? 

![](http://i.imgur.com/Sqon94a.png)

If so unblock the file and try again.

**Comment by DizzyAvocado** [comment]
I don't know if Bluefrost13 did the same thing but I what I did to install it was download the zip from my tablet, then unzip it and replace the files using Solid Explorer with root permissions. I didn't use my computer at all, maybe that's causing the issue. I'll try again later using my computer and see if it works.

**Comment by Bluefrost13** [comment]
I was originally doing this on my phone, but i tried it on windows to check the CRC32.  Unblocked the zip, verified the integrity, moved the files, and it still goes to the black screen.

**Comment by Renari** [comment]
I've been able to track down what is causing this. It's an unauthorized access exception it occurs when the game doesn't have permission to access the files.

Please confirm that the owner of the files after you copy them is com.aniplex.fategrandorder.

**Comment by DizzyAvocado** [comment]
I'm gonna check in a second. If this works, it means that all the re-rollers from the first two days could've had a much easier time by just replacing the authsave.dat and signupsave.dat with a save from just before rolling instead of deleting them and playing through the tutorial over and over again.

**Comment by Renari** [comment]
I don't know what your talking about :\ all that is in those files is authkeys for accessing your current session on the server and the username you chose. Replacing these files would not have made rerolling any easier. That said, I'm glad you got the issue fixed.

**Comment by DizzyAvocado** [comment]
Yeah you might be right, I'm going to try doing that on an emulator later. Anyway I hope this fixes Bluefrost13 problem as well. If anyone else is having this issue, I should mention I used Solid Explorer to change the permissions of both files by editing their properties. You can check other files from the folder to see which app is the one you have to give permissions to, though it has the F/GO icon so there's not much of a problem there.

**Comment by Bluefrost13** [comment]
Solution worked great.  Thanks for everything!
