### ISSUE TITLE
Cant get this to work

### ISSUE THREAD

**Issue by PanicPacman** [Renari/Fate-Grand-Order-Translation#6]
Erm i cant seem to get it working, i have to change the files in the location specified which i did but still does not work, must the file specifically be in data/data? pls help thank you :)

**Comment by Renari** [comment]
You shouldn't have to change any files.

**Comment by PanicPacman** [comment]
oh then i must be doing something wrong T.T then what do i have to do?
i downloaded the apk and installed it already

**Comment by Renari** [comment]
That's it.

**Comment by PanicPacman** [comment]
errr the apk is the "Fate/GO translation" right? sorry *i cant install it T.T its says
"an error has occurred. you probably dont have root. unable to get guid/uid"

**Comment by Renari** [comment]
Then your phone isn't rooted.

**Comment by PanicPacman** [comment]
dont get the rooted thing, as in modified?

**Comment by Renari** [comment]
http://lifehacker.com/5789397/the-always-up-to-date-guide-to-rooting-any-android-phone

**Comment by PanicPacman** [comment]
errrrr i've rooted my phone but still not working!

**Comment by Renari** [comment]
"still not working" is not an error
