### ISSUE TITLE
Hello I have a question for you ^^

### ISSUE THREAD

**Issue by Roxxyy** [Renari/Fate-Grand-Order-Translation#7]
Hello, first of all I want to thank you for this great work you are doing, and also congratulate you on how well this running. I introduce myself, I am a girl who is dedicated to the translation amateur games I like, people tend to like him much my translations and do for everyone, lately many people have asked me to translate this game (my language is the Spanish) and the truth is that I found all the files but I can not edit my hexadecimal editor (this is what I use to access the text of most games) so I wanted to ask if you can tell me you use to extract the .dat files and re-compress. (name of program or tool you use)

We would be very grateful, because I have searched the internet and as a result nothing  T.T

A kiss and thanks for everything. ^^

**Comment by Renari** [comment]
Hello, as you can see in #1 I am not willing to give out the information to edit the dat files as it has potential to be abused.

**Comment by Roxxyy** [comment]
Abused? I can do as an abuse edit these files? Well, then what do you think if I pass the translated text into my language and you do .dat files or .apk installation?

**Comment by Roxxyy** [comment]
You can give me an answer please?

**Comment by Renari** [comment]
I'm not willing to pick up additional translations at this time as the current one isn't finished.

**Comment by Roxxyy** [comment]
so laborious to create the dat file with the translated texts that I would give you?
