### ISSUE TITLE
Further details Required 

### ISSUE THREAD

**Issue by Maytriss** [Renari/Fate-Grand-Order-Translation#8]
Hello

I would like ask about why your installer needs root access and what exactly is translated into English, after visiting the android forums I am hesitant open the Pandora's box that is rooting my tablet just for something that may or may not satisfy my hopes on what your program does. 

I would also like to create a wiki which would answer basic questions about this program.

Thank you for your time

**Comment by Renari** [comment]
Yes, the installer needs root access however I have removed all links to the old installer because I'm working on a better way to handle those files.  If you have the old installer I advise you not to use it.

**Comment by Maytriss** [comment]
... putting that aside when do you hope to have it completed? I mainly ask this to see whether or not to hold off playing the Main Story until your installer is ready to be used.

**Comment by Renari** [comment]
You can replay all of the story cutscenes in your room. When it will be completed depends entirely upon when the translation is complete at this point.

**Comment by Maytriss** [comment]
coolies, I already knew this I just imagine it would more 'satisfying' actually following the story. ^^ 

I look forward to able to know what my servant skills are without memorising  them.
