### ISSUE TITLE
How to Install

### ISSUE THREAD

**Issue by Sarabveer** [Renari/Fate-Grand-Order-Translation#9]
Since @Renari is making a new apk. How do we install this manually in F/GO 1.0.4

**Comment by Renari** [comment]
You cannot, the installer is going to have to unpack and repack files which there is no tool to do manually.

**Comment by Sarabveer** [comment]
Any ETA on the Installer

**Comment by Renari** [comment]
No, because the translation files are not complete.

**Comment by Sarabveer** [comment]
So, can I just get  the old installer apk.

I really need some sort of Engrish in the game.

**Comment by Renari** [comment]
Unfortunately no, it was removed because the implementation is unstable and will cause problems in the game.

**Comment by Sarabveer** [comment]
:(
